import { prisma } from "./prisma";
import { deployMode } from "./env";

/** JSON-снимок воркспейса для переноса на другую машину (без секретов каналов и webhook). */
export async function buildWorkspaceExport(workspaceId: string) {
  const ws = await prisma.workspace.findUniqueOrThrow({ where: { id: workspaceId } });
  const [
    contacts,
    leads,
    customFields,
    fieldValues,
    knowledgeTopics,
    knowledgeArticles,
    tags,
    leadTags,
    flows,
    flowBlocks,
    aiProcesses,
    modelBindings,
    channels,
    autoAssignRules,
    cannedReplies,
  ] = await Promise.all([
    prisma.contact.findMany({ where: { workspaceId } }),
    prisma.lead.findMany({ where: { workspaceId } }),
    prisma.customField.findMany({ where: { workspaceId } }),
    prisma.fieldValue.findMany({ where: { workspaceId } }),
    prisma.knowledgeTopic.findMany({ where: { workspaceId } }),
    prisma.knowledgeArticle.findMany({ where: { workspaceId } }),
    prisma.tag.findMany({ where: { workspaceId } }),
    prisma.leadTag.findMany({ where: { workspaceId } }),
    prisma.flow.findMany({ where: { workspaceId } }),
    prisma.flowBlock.findMany({ where: { workspaceId } }),
    prisma.aiProcess.findMany({ where: { workspaceId } }),
    prisma.modelBinding.findMany({ where: { workspaceId } }),
    prisma.channel.findMany({ where: { workspaceId } }),
    prisma.autoAssignRule.findMany({ where: { workspaceId } }),
    prisma.cannedReply.findMany({ where: { workspaceId } }),
  ]);

  return {
    exportVersion: 1,
    exportedAt: new Date().toISOString(),
    deployMode: deployMode(),
    settings: {
      name: ws.name,
      tradeDescription: ws.tradeDescription,
      defaultModel: ws.defaultModel,
      greeting: ws.greeting,
      chatGreeting: ws.chatGreeting,
      salesPrompt: ws.salesPrompt,
      slaMinutes: ws.slaMinutes,
      pingEnabled: ws.pingEnabled,
      routingMode: ws.routingMode,
      workHoursEnabled: ws.workHoursEnabled,
      workHoursStart: ws.workHoursStart,
      workHoursEnd: ws.workHoursEnd,
      workHoursTz: ws.workHoursTz,
      outboundWebhookConfigured: Boolean(ws.outboundWebhookUrl),
    },
    contacts: contacts.map((c) => ({
      id: c.id,
      name: c.name,
      phone: c.phone,
      comment: c.comment,
      consentAt: c.consentAt,
      createdAt: c.createdAt,
    })),
    leads: leads.map((l) => ({
      id: l.id,
      contactId: l.contactId,
      status: l.status,
      source: l.source,
      comment: l.comment,
      urgent: l.urgent,
      rejectReason: l.rejectReason,
      createdAt: l.createdAt,
    })),
    customFields,
    fieldValues,
    knowledge: {
      topics: knowledgeTopics,
      articles: knowledgeArticles.map((a) => ({
        id: a.id,
        topicId: a.topicId,
        title: a.title,
        body: a.body,
        enabled: a.enabled,
      })),
    },
    tags,
    leadTags,
    flows,
    flowBlocks: flowBlocks.map((b) => ({
      ...b,
      config: b.config,
    })),
    aiProcesses: aiProcesses.map((p) => ({ id: p.id, type: p.type, name: p.name, prompt: p.prompt })),
    modelBindings,
    channels: channels.map((c) => ({
      id: c.id,
      type: c.type,
      name: c.name,
      publicKey: c.publicKey,
      enabled: c.enabled,
      config: c.config,
      hasSecrets: Boolean(c.secretsEnc),
    })),
    autoAssignRules: autoAssignRules.map((r) => ({
      channel: r.channel,
      tagName: r.tagName,
      assigneeId: r.assigneeId,
      sortOrder: r.sortOrder,
      enabled: r.enabled,
    })),
    cannedReplies: cannedReplies.map((c) => ({ title: c.title, body: c.body })),
  };
}
